// Users
export const GET_USER_FETCHING = 'GET_USER_FETCHING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

// Company
export const GET_COMPANY_FETCHING = 'GET_COMPANY_FETCHING'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'

// Document
export const CREATE_DOCUMENT_FETHCING = 'CREATE_DOCUMENT_FETHCING'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_FETCHING = 'GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_FETCHING'
export const GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS'

// Drafts
export const GET_DRAFTS_BY_ACTIVE_COMPANY_ID_FETCHING = 'GET_DRAFTS_BY_ACTIVE_COMPANY_ID_FETCHING'
export const GET_DRAFTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_DRAFTS_BY_ACTIVE_COMPANY_ID_SUCCESS'
