// Users
export const GET_USER_FETCHING = 'GET_USER_FETCHING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const UPDATE_USER_FETCHING = 'UPDATE_USER_FETCHING'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

// Company
export const GET_COMPANY_FETCHING = 'GET_COMPANY_FETCHING'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_BY_ID_FETCHING = 'GET_COMPANY_BY_ID_FETCHING'
export const GET_COMPANY_BY_ID_SUCCESS = 'GET_COMPANY_BY_ID_SUCCESS'
export const CHANGE_ACTIVE_COMPANY_BY_ID_FETCHING = 'CHANGE_ACTIVE_COMPANY_BY_ID_FETCHING'
export const CHANGE_ACTIVE_COMPANY_BY_ID_SUCCESS = 'CHANGE_ACTIVE_COMPANY_BY_ID_SUCCESS'
export const CREATE_COMPANY_FETCHING = 'CREATE_COMPANY_FETCHING'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'

// Documents
export const GET_DOCUMENTS_BY_ACTIVE_COMPANY_ID_FETCHING = 'GET_DOCUMENTS_BY_ACTIVE_COMPANY_ID_FETCHING'

export const REMOVE_DOCUMENT_BY_ID_FETCHING = 'REMOVE_DOCUMENT_BY_ID_FETCHING'
export const REMOVE_DOCUMENTS_BY_IDS_FETCHING = 'REMOVE_DOCUMENTS_BY_IDS_FETCHING'

export const SEND_DOCUMENT_TO_USER_FETCHING = 'SEND_DOCUMENT_TO_USER_FETCHING'
export const SEND_DOCUMENT_TO_USER_SUCCESS = 'SEND_DOCUMENT_TO_USER_SUCCESS'

// inbox documents
export const GET_INBOX_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_INBOX_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS'
export const REMOVE_INBOX_DOCUMENT_BY_ID_SUCCESS = 'REMOVE_INBOX_DOCUMENT_BY_ID_SUCCESS'
export const REMOVE_INBOX_DOCUMENTS_BY_IDS_SUCCESS = 'REMOVE_INBOX_DOCUMENTS_BY_IDS_SUCCESS'

// out documents
export const GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_OUT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS'
export const REMOVE_OUT_DOCUMENT_BY_ID_SUCCESS = 'REMOVE_OUT_DOCUMENT_BY_ID_SUCCESS'
export const REMOVE_OUT_DOCUMENTS_BY_IDS_SUCCESS = 'REMOVE_INBOX_DOCUMENTS_BY_IDS_SUCCESS'

// draft documents
export const GET_DRAFT_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_DRAFTS_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS'
export const REMOVE_DRAFT_DOCUMENT_BY_ID_SUCCESS = 'REMOVE_DRAFT_DOCUMENT_BY_ID_SUCCESS'
export const REMOVE_DRAFT_DOCUMENTS_BY_IDS_SUCCESS = 'REMOVE_DRAFT_DOCUMENTS_BY_IDS_SUCCESS'

// archive documents
export const GET_ARCHIVE_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS = 'GET_ARCHIVE_DOCUMENTS_BY_ACTIVE_COMPANY_ID_SUCCESS'
export const REMOVE_ARCHIVE_DOCUMENT_BY_ID_SUCCESS = 'REMOVE_ARCHIVE_DOCUMENT_BY_ID_SUCCESS'
export const REMOVE_ARCHIVE_DOCUMENTS_BY_IDS_SUCCESS = 'REMOVE_ARCHIVE_DOCUMENTS_BY_IDS_SUCCESS'

// single document
export const CREATE_DOCUMENT_FETHCING = 'CREATE_DOCUMENT_FETHCING'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const GET_DOCUMENT_BY_ID_FETCHING = 'GET_DOCUMENT_BY_ID_FETCHING'
export const GET_DOCUMENT_BY_ID_SUCCESS = 'GET_DOCUMENT_BY_ID_SUCCESS'
export const VERIFY_DOCUMENT_FETCHING = 'VERIFY_DOCUMENT_FETCHING'
export const VERIFY_DOCUMENT_SUCCESS = 'VERIFY_DOCUMENT_SUCCESS'
export const UPDATE_DOCUMENT_BY_ID_FETCHING = 'UPDATE_DOCUMENT_BY_ID_FETCHING'
export const UPDATE_DOCUMENT_BY_ID_SUCCESS = 'UPDATE_DOCUMENT_BY_ID_SUCCESS'
